DROP TABLE IF EXISTS PLAYER, TEAM, STATE, COLOR;

CREATE TABLE COLOR
(
    COLOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(100)
);

CREATE TABLE STATE
(
    STATE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(255)
);

CREATE TABLE TEAM
(
    TEAM_ID  INT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(100),
    STATE_ID INT,
    COLOR_ID INT,
    WINS     INT,
    LOSSES   INT,
    FOREIGN KEY (STATE_ID) REFERENCES STATE (STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR (COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PLAYER
(
    PLAYER_ID   INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_ID     INT,
    UNIFORM_NUM INT,
    FIRST_NAME  VARCHAR(100),
    LAST_NAME   VARCHAR(100),
    MPG         INT,
    PPG         INT,
    RPG         INT,
    APG         INT,
    SPG         DOUBLE PRECISION,
    BPG         DOUBLE PRECISION,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);
